- id: python-black
  name: black (Python)
  description: "Black: The uncompromising Python code formatter"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: --entrypoint black testthedocs/black:22.1.0
  types: [python]
- id: python-isort
  name: isort (Python)
  description: "Sort your imports, so you don't have to"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: --entrypoint isort testthedocs/isort:5.7.0
  args: ["--profile", "black", "--filter-files"]
  types: [python]
- id: vale
  name: vale
  description: "Vale prose linter"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: testthedocs/vale:2.15.5
  types: [markdown]
