- id: python-black
  name: black (Python)
  description: "Black: The uncompromising Python code formatter"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: --entrypoint black testthedocs/black:22.12.0
  types: [python]
- id: python-isort
  name: isort (Python)
  description: "Sort your imports, so you don't have to"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: --entrypoint isort testthedocs/isort:5.11.1
  args: ["--profile", "black", "--filter-files"]
  types: [python]
- id: vale
  name: vale
  description: "Vale prose linter"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: testthedocs/vale:2.21.3
  types: [markdown]
- id: markdown-lint
  name: markdown-lint
  description: "Markdown Lint"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: testthedocs/markdownlint:0.31.1
  types: [markdown]
- id: cspell-openapi
  name: Spell check OpenAPI
  description: "Cspell spell check OpenAPI"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: testthedocs/cspell:6.17.0
  files: openapi.*\.yaml$
  types: [file]
- id: spectral
  name: Running spectral against openapi.yaml
  description: "Running spectral against openapi.yaml"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: testthedocs/spectral:6.6.0
  files: openapi.*\.yaml$
  types: [file]
- id: alex
  name: alex-lint
  description: "Catch insensitive, inconsiderate writing"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: testthedocs/alex:11.0.0
  types: [markdown]