- id: python-black
  name: black (Python)
  description: "Black: The uncompromising Python code formatter"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: --entrypoint black testthedocs/black:$VERSION
  types: [python]
- id: pthon-isort
  name: isort (Python)
  description: "Sort your imports, so you don't have to"
  minimum_pre_commit_version: '2.17.0'
  language: docker_image
  entry: --entrypoint isort testthedocs/isort:$VERSION
  types: [python]
